// flow-typed signature: 9b61cd92b5322e8c22d8b0b96017632e
// flow-typed version: <<STUB>>/react-cookies_v^0.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cookies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cookies' {
    declare module .exports: any
;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cookies/__tests__/index' {
    declare module .exports: any
;
}

declare module 'react-cookies/build/cookie' {
    declare module .exports: any
;
}

// Filename aliases
declare module 'react-cookies/__tests__/index.js' {
    declare module .exports: $Exports<'react-cookies/__tests__/index'>
;
}
declare module 'react-cookies/build/cookie.js' {
    declare module .exports: $Exports<'react-cookies/build/cookie'>
;
}
