// flow-typed signature: 3a780b5fe95e83eacaf35bf06304df1b
// flow-typed version: <<STUB>>/react-parallax_v^1.8.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-parallax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-parallax' {
    declare module .exports: any
;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-parallax/dist/index' {
    declare module .exports: any
;
}

declare module 'react-parallax/karma.conf' {
    declare module .exports: any
;
}

declare module 'react-parallax/setupFile' {
    declare module .exports: any
;
}

declare module 'react-parallax/src/kitchensink/index' {
    declare module .exports: any
;
}

declare module 'react-parallax/src/kitchensink/KitchenSink' {
    declare module .exports: any
;
}

declare module 'react-parallax/src/kitchensink/PageOne' {
    declare module .exports: any
;
}

declare module 'react-parallax/src/kitchensink/PageThree' {
    declare module .exports: any
;
}

declare module 'react-parallax/src/kitchensink/PageTwo' {
    declare module .exports: any
;
}

declare module 'react-parallax/src/modules/Background' {
    declare module .exports: any
;
}

declare module 'react-parallax/src/modules/index' {
    declare module .exports: any
;
}

declare module 'react-parallax/src/modules/Parallax' {
    declare module .exports: any
;
}

declare module 'react-parallax/src/util/Util' {
    declare module .exports: any
;
}

declare module 'react-parallax/src/util/util.test' {
    declare module .exports: any
;
}

declare module 'react-parallax/webpack.config.build' {
    declare module .exports: any
;
}

declare module 'react-parallax/webpack.config.dev' {
    declare module .exports: any
;
}

declare module 'react-parallax/webpack.config' {
    declare module .exports: any
;
}

// Filename aliases
declare module 'react-parallax/dist/index.js' {
    declare module .exports: $Exports<'react-parallax/dist/index'>
;
}
declare module 'react-parallax/karma.conf.js' {
    declare module .exports: $Exports<'react-parallax/karma.conf'>
;
}
declare module 'react-parallax/setupFile.js' {
    declare module .exports: $Exports<'react-parallax/setupFile'>
;
}
declare module 'react-parallax/src/kitchensink/index.js' {
    declare module .exports: $Exports<'react-parallax/src/kitchensink/index'>
;
}
declare module 'react-parallax/src/kitchensink/KitchenSink.js' {
    declare module .exports: $Exports<'react-parallax/src/kitchensink/KitchenSink'>
;
}
declare module 'react-parallax/src/kitchensink/PageOne.js' {
    declare module .exports: $Exports<'react-parallax/src/kitchensink/PageOne'>
;
}
declare module 'react-parallax/src/kitchensink/PageThree.js' {
    declare module .exports: $Exports<'react-parallax/src/kitchensink/PageThree'>
;
}
declare module 'react-parallax/src/kitchensink/PageTwo.js' {
    declare module .exports: $Exports<'react-parallax/src/kitchensink/PageTwo'>
;
}
declare module 'react-parallax/src/modules/Background.js' {
    declare module .exports: $Exports<'react-parallax/src/modules/Background'>
;
}
declare module 'react-parallax/src/modules/index.js' {
    declare module .exports: $Exports<'react-parallax/src/modules/index'>
;
}
declare module 'react-parallax/src/modules/Parallax.js' {
    declare module .exports: $Exports<'react-parallax/src/modules/Parallax'>
;
}
declare module 'react-parallax/src/util/Util.js' {
    declare module .exports: $Exports<'react-parallax/src/util/Util'>
;
}
declare module 'react-parallax/src/util/util.test.js' {
    declare module .exports: $Exports<'react-parallax/src/util/util.test'>
;
}
declare module 'react-parallax/webpack.config.build.js' {
    declare module .exports: $Exports<'react-parallax/webpack.config.build'>
;
}
declare module 'react-parallax/webpack.config.dev.js' {
    declare module .exports: $Exports<'react-parallax/webpack.config.dev'>
;
}
declare module 'react-parallax/webpack.config.js' {
    declare module .exports: $Exports<'react-parallax/webpack.config'>
;
}
