// flow-typed signature: 16853f6db05fedcbc762313984fc08e7
// flow-typed version: <<STUB>>/webpack-monitor_v^1.0.14/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-monitor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-monitor' {
    declare module .exports: any
;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-monitor/build/app' {
    declare module .exports: any
;
}

declare module 'webpack-monitor/monitor' {
    declare module .exports: any
;
}

declare module 'webpack-monitor/utils/parser' {
    declare module .exports: any
;
}

declare module 'webpack-monitor/utils/server' {
    declare module .exports: any
;
}

// Filename aliases
declare module 'webpack-monitor/build/app.js' {
    declare module .exports: $Exports<'webpack-monitor/build/app'>
;
}
declare module 'webpack-monitor/monitor.js' {
    declare module .exports: $Exports<'webpack-monitor/monitor'>
;
}
declare module 'webpack-monitor/utils/parser.js' {
    declare module .exports: $Exports<'webpack-monitor/utils/parser'>
;
}
declare module 'webpack-monitor/utils/server.js' {
    declare module .exports: $Exports<'webpack-monitor/utils/server'>
;
}
