// flow-typed signature: 340e2b0a99e0fe96e62b8a6c77be24e5
// flow-typed version: <<STUB>>/webpack-unused_v^0.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-unused'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-unused' {
    declare module .exports: any
;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-unused/index' {
    declare module .exports: $Exports<'webpack-unused'>
;
}
declare module 'webpack-unused/index.js' {
    declare module .exports: $Exports<'webpack-unused'>
;
}
